Repository RedHatQE/openshift-ci-trigger, pull requests merged in 2023-05, with the labels that each got.

#1 trigger_openshift_ci_job - start job
  app/app.py
  example.config.yaml
Labels: size/S, branch-main, Approved-by-myakove

#4 Fix test job name
  app/app.py
Labels: branch-main, size/XS

#16 Fix update operators IIB file
  Dockerfile
  app/app.py
  operators-latest-iib.json
  poetry.lock
Labels: branch-main, verified, size/XXL

#19 Set full path for iib index image
  app/app.py
  operators-latest-iib.json
Labels: branch-main, size/XS, verified, Approved-by-rnetser, can-be-merged
