Repository RedHatQE/openshift-ci-trigger, pull requests merged in 2023-07, with the labels that each got.

#38 Remove renamed job
  operators-latest-iib.json
Labels: size/S, branch-main, Approved-by-myakove, verified, can-be-merged

#40 Update logic to get job names from config
  app/app.py
Labels: branch-main, Approved-by-myakove, verified, can-be-merged, size/M

#44 Poetry: set versions for modules
  app/app.py
  poetry.lock
  pyproject.toml
Labels: branch-main, verified, size/XL, Approved-by-rnetser, can-be-merged

#42 Support multiple jobs per addon
  app/app.py
  example.config.yaml
Labels: size/S, branch-main, verified

#48 Reset json file after job rename
  operators-latest-iib.json
Labels: branch-main, size/XS, verified
